import elonGif from "./media/elon.gif";
import landscape from "./media/landscape.jpg";

export const tweetsArray = [
  {
    id: 1,
    profilePic: 'https://robohash.org/1',
    profileName: 'Will Jones',
    postText: 'Just had a great day at the beach!',
    media: elonGif
  },
  {
    id: 2,
    profilePic: 'https://robohash.org/2',
    profileName: 'Jane Smith',
    postText: 'Excited for the weekend getaway!',
    media: landscape
  },
  {
    id: 3,
    profilePic: 'https://robohash.org/3',
    profileName: 'Alex Johnson',
    postText: 'Enjoying the new book I just started reading. It has been such an amazing journey diving into the world of characters and plots. Can\'t wait to see how it ends!',
  },
  {
    id: 4,
    profilePic: 'https://robohash.org/4',
    profileName: 'Sarah Thompson',
    postText: 'Had an amazing dinner at my favorite restaurant. The food was delicious, and the company was even better. Looking forward to more such delightful evenings.',
  },
  {
    id: 5,
    profilePic: 'https://robohash.org/5',
    profileName: 'Michael Lee',
    postText: 'Excited to announce my new project! After months of hard work and dedication, it\'s finally ready to launch. Can\'t wait to share it with everyone!',
  },
  {
    id: 6,
    profilePic: 'https://robohash.org/6',
    profileName: 'Emily Rodriguez',
    postText: 'Feeling grateful for all the love and support. I have the most amazing friends and family, and I couldn\'t be more thankful for their presence in my life.',
  },
  {
    id: 7,
    profilePic: 'https://robohash.org/7',
    profileName: 'David Wilson',
    postText: 'Enjoying a peaceful evening walk in the park. There\'s something magical about the tranquility of nature. It helps me unwind and find solace in the midst of a busy day.',
  },
  {
    id: 8,
    profilePic: 'https://robohash.org/8',
    profileName: 'Olivia Martinez',
    postText: 'Can\'t wait for the new movie release! I\'m a huge fan of the franchise, and this sequel promises to be even more thrilling than the previous ones.',
  },
  {
    id: 9,
    profilePic: 'https://robohash.org/9',
    profileName: 'Matthew Davis',
    postText: 'This is the only post I wrote manually, all the rest are generated by Chat-gpt',
  },
  {
    id: 10,
    profilePic: 'https://robohash.org/10',
    profileName: 'Emma Brown',
    postText: 'Spending quality time with family this weekend. We\'re planning a fun picnic in the park, followed by some board games and laughter. Can\'t wait for the memories!',
  },
]



export const topHashtags = [
  {topic: "Formula 1 -Trending", title: "Lewis Hamilton", tweetsNum: "4926"},
  {topic: "Trending in Argentina", title: "Lionel Messi", tweetsNum: "2926"},
  {topic: "Music - Trending", title: "Ariana Grande", tweetsNum: "24k"},
  {topic: "Sports - Trending", title: "Usain Bolt", tweetsNum: "1940"},
]
